<a href="https://colab.research.google.com/github/Sukhi24397/Pract0/blob/main/Experiment20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#sukhi n
#25070123112
#covid data analysis

In [16]:
import pandas as pd
import numpy as np

In [22]:
data = pd.read_csv('/covid_19_data.csv', on_bad_lines='skip')
data.head()

/tmp/ipykernel_3191/1779857621.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('/covid_19_data.csv', on_bad_lines='skip')

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [23]:
data = data.drop(['SNo','Last Update'],axis=1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [24]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368571 entries, 0 to 368570
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  368571 non-null  object
 1   Province/State   276538 non-null  object
 2   Country/Region   368571 non-null  object
 3   Confirmed        368568 non-null  float64
 4   Deaths           368567 non-null  float64
 5   Recovered        368567 non-null  float64
dtypes: float64(3), object(3)
memory usage: 16.9+ MB

In [27]:
data['ObservationDate'] = pd.to_datetime(data['ObservationDate'], errors='coerce')
data['Confirmed'] = data['Confirmed'].fillna(0).astype('int64')
data['Deaths'] = data['Deaths'].fillna(0).astype('int64')
data['Recovered'] = data['Recovered'].fillna(0).astype('int64')

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 368571 entries, 0 to 368570
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  368569 non-null  datetime64[ns]
 1   Province/State   276538 non-null  object
 2   Country/Region   368571 non-null  object
 3   Confirmed        368571 non-null  int64
 4   Deaths           368571 non-null  int64
 5   Recovered        368571 non-null  int64
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 16.9+ MB

In [29]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      2020-01-22          Anhui  Mainland China          1       0          0
1      2020-01-22        Beijing  Mainland China         14       0          0
2      2020-01-22      Chongqing  Mainland China          6       0          0
3      2020-01-22         Fujian  Mainland China          1       0          0
4      2020-01-22          Gansu  Mainland China          0       0          0

In [31]:
### Active Case
data['Active'] = data['Confirmed'] - data['Recovered'] - data['Deaths']
data.head(50)

data.iloc[50:100]

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
50,2020-01-23,Heilongjiang,Mainland China,2,0,0,2
51,2020-01-23,Henan,Mainland China,5,0,0,5
52,2020-01-23,Hong Kong,Hong Kong,2,0,0,2
53,2020-01-23,Hubei,Mainland China,444,17,28,399
54,2020-01-23,Hunan,Mainland China,9,0,0,9
55,2020-01-23,Inner Mongolia,Mainland China,0,0,0,0
56,2020-01-23,Jiangsu,Mainland China,5,0,0,5
57,2020-01-23,Jiangxi,Mainland China,7,0,0,7
58,2020-01-23,Jilin,Mainland China,1,0,0,1
59,2020-01-23,Liaoning,Mainland China,3,0,0,3
60,2020-01-23,Macau,Macau,2,0,0,2
61,2020-01-23,Ningxia,Mainland China,1,0,0,1
62,2020-01-23,Qinghai,Mainland China,0,0,0,0
63,2020-01-23,Shaanxi,Mainland China,3,0,0,3
64,2020-01-23,Shandong,Mainland China,6,0,0,6
65,2020-01-23,Shanghai,Mainland China,16,0,0,16
66,2020-01-23,Shanxi,Mainland China,1,0,0,1
67,2020-01-23,Sichuan,Mainland China,8,0,0,8
68,2020-01-23,Taiwan,Taiwan,1,0,0,1
69,2020-01-23,Tianjin,Mainland China,4,0,0,4
70,2020-01-23,Tibet,Mainland China,0,0,0,0
71,2020-01-23,Washington,US,1,0,0,1
72,2020-01-23,Xinjiang,Mainland China,2,0,0,2
73,2020-01-23,Yunnan,Mainland China,2,0,0,2
74,2020-01-23,Zhejiang,Mainland China,27,0,0,27
75,2020-01-23,NaN,Japan,1,0,0,1
76,2020-01-23,NaN,Thailand,4,0,2,2
77,2020-01-23,NaN,South Korea,1,0,0,1
78,2020-01-23,NaN,Singapore,1,0,0,1
79,2020-01-23,NaN,Philippines,0,0,0,0
80,2020-01-23,NaN,Malaysia,0,0,0,0
81,2020-01-23,NaN,Vietnam,2,0,0,2
82,2020-01-23,NaN,Australia,0,0,0,0
83,2020-01-23,NaN,Mexico,0,0,0,0
84,2020-01-23,NaN,Brazil,0,0,0,0
85,2020-01-23,NaN,Colombia,0,0,0,0
86,2020-01-23,Unknown,China,0,0,0,0
87,2020-01-23,NaN,Kiribati,0,0,0,0
88,2020-01-24,Hubei,Mainland China,549,24,31,494
89,2020-01-24,Guangdong,Mainland China,53,0,2,51
90,2020-01-24,Zhejiang,Mainland China,43,0,1,42
91,2020-01-24,Beijing,Mainland China,36,0,1,35
92,2020-01-24,Chongqing,Mainland China,27,0,0,27
93,2020-01-24,Hunan,Mainland China,24,0,0,24
94,2020-01-24,Guangxi,Mainland China,23,0,0,23
95,2020-01-24,Shanghai,Mainland China,20,0,1,19
96,2020-01-24,Jiangxi,Mainland China,18,0,0,18
97,2020-01-24,Sichuan,Mainland China,15,0,0,15
98,2020-01-24,Shandong,Mainland China,15,0,0,15
99,2020-01-24,Anhui,Mainland China,15,0,0,15

In [32]:
### last/current date
data['ObservationDate'].max()

Timestamp('2021-05-29 00:00:00')

In [33]:
### Fetch the latest date data
latest_data = data[data['ObservationDate'] == data['ObservationDate'].max()]
latest_data.head()

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
136866,2021-05-29,NaN,Afghanistan,70111,2899,57281,9931
136867,2021-05-29,NaN,Albania,132297,2449,129215,633
136868,2021-05-29,NaN,Algeria,128456,3460,89419,35577
136869,2021-05-29,NaN,Andorra,13693,127,13416,150
136870,2021-05-29,NaN,Angola,34180,757,27646,5777

In [34]:
latest_data.shape

(1530, 7)

In [35]:
latest_data['Country/Region'].value_counts()

Country/Region
Russia                166
US                    116
Japan                  98
India                  74
Colombia               68
                     ...
Venezuela               2
Vietnam                 2
West Bank and Gaza      2
Hong Kong               2
Macau                   2
Name: count, Length: 195, dtype: int64

In [36]:
latest_data['Country/Region'].nunique()

195

In [37]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Micronesia',
       'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco',
       'Mozambique', 'Namibia', 'Nepal', 'New Zealand', 'Nicaragua',
       'Niger', 'Nigeria', 'North Macedonia', 'Norway', 'Oman', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Philippines', 'Poland',
       'Portugal', 'Qatar', 'Romania', 'Rwanda', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa',
       'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia',
       'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa',
       'South Korea', 'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Uganda', 'United Arab Emirates', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'West Bank and Gaza', 'Yemen', 'Zambia', 'Zimbabwe', 'Italy',
       'Brazil', 'Russia', 'Mexico', 'Japan', 'US', 'Canada', 'Colombia',
       'Peru', 'Spain', 'India', 'UK', 'Mainland China', 'Chile',
       'Belgium', 'Netherlands', 'Australia', 'Pakistan', 'Germany',
       'Sweden', 'Ukraine', 'Hong Kong', 'Macau'], dtype=object)

In [38]:
## Count of cases for each country
countries = latest_data.groupby("Country/Region")[["Confirmed","Deaths","Recovered","Active"]].sum()

countries = countries.reset_index()

In [39]:
countries

         Country/Region  Confirmed  Deaths  Recovered  Active
0           Afghanistan     140222    5798     114562   19862
1               Albania     264594    4898     258430    1266
2               Algeria     256912    6920     178838   71154
3               Andorra      27386     254      26832     300
4                Angola      68360    1514      55292   11554
..                  ...        ...     ...        ...     ...
190             Vietnam      13816      94       5792    7930
191  West Bank and Gaza     615676    6984     601048    7644
192               Yemen      13462    2638       6798    4026
193              Zambia     189502    2552     183188    3762
194            Zimbabwe      77866    3188      73156    1522

[195 rows x 5 columns]

In [40]:
countries[countries['Country/Region']=="Mainland China"]

     Country/Region  Confirmed  Deaths  Recovered  Active
107  Mainland China     182144    9272     172234     638

In [41]:
countries[countries['Country/Region']=="US"]

    Country/Region  Confirmed   Deaths  Recovered    Active
182             US   66503878  1188612          0  65315266

In [42]:
# Cases in India
countries[countries['Country/Region']=="India"]

   Country/Region  Confirmed  Deaths  Recovered   Active
78          India   55789600  651944   50908640  4229016

In [43]:
countries['Country/Region']=="Mainland China"

0      False
1      False
2      False
3      False
4      False
       ...
190    False
191    False
192    False
193    False
194    False
Name: Country/Region, Length: 195, dtype: bool

In [44]:
import plotly.express as px

In [45]:
world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color="Confirmed",color_continuous_scale="reds",range_color=[0,10000000])
world_map